version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:${OS_VER}
    container_name: opensearch-node1_${OS_VER}
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./config/security_plugin/config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
      - ./config/security_plugin/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
      - ./config/security_plugin/roles_mappings.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mappings.yml
      - ./config/security_plugin/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      - ./config/opensearch/sgadmin_restore.sh:/usr/share/opensearch/sgadmin_restore.sh
      - ./config/opensearch/sgadmin_backup.sh:/usr/share/opensearch/sgadmin_backup.sh
      - ./config/opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./config/opensearch/config/esnode-key.pem:/usr/share/opensearch/config/esnode-key.pem
      - ./config/opensearch/config/esnode.pem:/usr/share/opensearch/config/esnode.pem
      - ./config/opensearch/config/kirk-key.pem:/usr/share/opensearch/config/kirk-key.pem
      - ./config/opensearch/config/opensearch.keystore:/usr/share/opensearch/config/opensearch.keystore
      - ./config/opensearch/config/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-node2:
    image: opensearchproject/opensearch:${OS_VER}
    container_name: opensearch-node2_${OS_VER}
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ./config/security_plugin/config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
      - ./config/security_plugin/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
      - ./config/security_plugin/roles_mappings.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mappings.yml
      - ./config/security_plugin/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      - ./config/opensearch/sgadmin_restore.sh:/usr/share/opensearch/sgadmin_restore.sh
      - ./config/opensearch/sgadmin_backup.sh:/usr/share/opensearch/sgadmin_backup.sh
      - ./config/opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./config/opensearch/config/esnode-key.pem:/usr/share/opensearch/config/esnode-key.pem
      - ./config/opensearch/config/esnode.pem:/usr/share/opensearch/config/esnode.pem
      - ./config/opensearch/config/kirk-key.pem:/usr/share/opensearch/config/kirk-key.pem
      - ./config/opensearch/config/opensearch.keystore:/usr/share/opensearch/config/opensearch.keystore
      - ./config/opensearch/config/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:${OS_VER} 
    container_name: opensearch-dashboards_${OS_VER}
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch-node1:9200"]
    volumes:
      - ./config/opensearch-dashboards/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      - ./config/opensearch-dashboards/opensearch_dashboards.crt:/usr/share/opensearch-dashboards/config/opensearch_dashboards.crt
      - ./config/opensearch-dashboards/opensearch_dashboards.key:/usr/share/opensearch-dashboards/config/opensearch_dashboards.key
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1
      - opensearch-node2

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
